### ISSUE TITLE
error: numactl-libs-2.0.12-9.el8.x86_64.rpm: not an rpm package (or package manifest)

### ISSUE THREAD

**Issue by peijianju** [arangodb/oskar#281]
Hi, 
It seems `numactl-libs-2.0.12-9.el8.x86_64.rpm` is replaced by `numactl-libs-2.0.12-11.el8.x86_64.rpm`
on http://mirror.centos.org/centos/8/BaseOS/x86_64/os/Packages/

Any plan to update that?

Thank you

**Comment by KVS85** [comment]
@peijianju thank you for noticing that. Updated in https://github.com/arangodb/oskar/commit/4ae953c1a20f3442fffc4474016271bd540b9588.
